version: '3.7'

services:
  fleet:
    container_name: nestjs_api_e2e
    image: fleetomatic:0.0.1
    build:
      context: .
      target: development
    command: npm run test:e2e
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: le_user
      POSTGRES_PASSWORD: le_pwd
      POSTGRES_DB: le_db
      PG_DATA: /var/lib/postgresql/data
    networks:
      - nestjs-network
    volumes:
      - pgdata:/var/lib/postgresql/data-test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - nestjs-network

networks:
  nestjs-network:
volumes:
  pgdata:
